####NUMPY

In [1]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([(0,1,2),(1,2,3)])

In [3]:
print(b)

[[0 1 2]
 [1 2 3]]


In [6]:
####generator functions

a = np.zeros(shape=(2,3)) ###array 2d containing 2 rows and 3 columns with all zero

np.ones_like(a) ###array with equal shape of a but filled with 1

np.arange(start = 1, stop = 5) #### array with one dimension filled with number from start to stop-1

np.linspace(start = 0, stop = 1, num = 5) ###array with one dimension from start to stop with num elements

np.empty(shape = (1,2)) ##array with desired shape filled with randomn number

array([[-5.73021895e-300,  6.92155067e-310]])

In [ ]:
###Import (read file)

b = np.fromfile('path', sep = '\t', dtype = int) ###read from file

In [7]:
#### Random from distribution
import numpy.random as rand

rand.random_sample((2,3)) ##random float from uniform distribution [0,1]

rand.randint(low = 5, high = 11, size = (4,2)) ###integers from discrete uniform distribution [low,high]

rand.normal(loc=0, scale=1, size=100) ###float from normnal distribution

array([ 0.82315999,  1.73009617,  1.51582132,  0.78376433,  1.85319292,
       -0.23460212, -0.69968289, -0.58778108, -1.69886592,  0.73401821,
       -0.91434496, -0.27737916, -1.86473104,  1.31420598, -0.00272554,
        0.58377382, -0.02177501, -0.45598817,  2.16211887,  0.07856352,
       -0.37500729, -0.95847001,  0.10044705,  0.68693901, -0.64036182,
        1.48153007, -0.45883894, -0.15493134, -0.00506954,  1.34395855,
        0.07458453,  1.05296989,  1.10914979, -1.62996228, -2.30419893,
        2.08600836,  1.37157184, -0.68036456,  0.01142887,  0.84738045,
       -0.99944557, -0.09213467, -1.24958336,  0.86926661,  1.79246756,
        0.05644337,  1.77782002,  1.28115362,  0.75836514,  0.2521688 ,
        2.22704372,  1.10456984,  0.63643016,  0.38519802,  0.89141811,
        1.37556046,  0.09394403,  2.38681652,  1.45459031, -0.67845059,
        1.5032649 , -0.97572855, -0.12843714, -0.27081992, -1.13981664,
       -0.90961321, -1.71361478, -0.5451219 , -0.16817591, -1.18

In [15]:
a = np.arange(5)
b = np.array([[i**2 for i in a],[j**3 for j in a]])
print(b)

[[ 0  1  4  9 16]
 [ 0  1  8 27 64]]


In [19]:
### Multidimensional
a = np.fromfunction(lambda x,y: 10*x+y, (4,4), dtype=int) #### x an y are taken from coordinates

a[0,1] ###first row, second cloumn

a[-2:,:] ##second-last and last rows with all columns

a[-2:] ###if not specified, it consider to take all the elements from the unspecified dimensions

array([[20, 21, 22, 23],
       [30, 31, 32, 33]])

In [31]:
a = np.random.randint(10,100,10)

idx = np.array([0,3,5,2,2])
a[idx]

bool_idx = np.array([i%2==0 for i in a])
a[bool_idx]
print(bool_idx)

[False False False False False False  True  True False False]


In [40]:
b = np.array([[[0,1,2],[7,8,9],[1,2,3]], [[2,3,4],[5,6,7],[3,4,5]]])

b[1,...,0] # interpreted as b[1,:,0]
# [2,3]

array([2, 5, 3])